### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by Sinfolke** [ASDAlexander77/TypeScriptCompiler#103]
On Windows when i try to use import from another file it shows an error: 
![Снимок экрана 2024-07-25 161740](https://github.com/user-attachments/assets/0771a1b2-5bd2-4172-8e0b-92c3ef224066)
In console then it outputs:
```
test.ts:1:1: error: String.ts: Can't open: Unknown error (0xC1)
import String from 'String.ts';
^
test.ts:1:1: error: failed statement
import String from 'String.ts';
^
```
if the file is not with extensoin .ts the program waits for several seconds and quit out.
I assume it attempts to run the file but it is a text document

**Comment by ASDAlexander77** [comment]
can u show me the code which u are using.

import has specific requirements, it is not as in real typescript.

if you put "typescript" file (without .ts at the end but with actual file at the same location) into import it will try to compile it into code .. 

if you compiler dll using tsc --emit=dll it will try to import dll dynamically u do not need to have typescript file for it.  
if you try to import dll in import which is created in c++ you need to declare all functions/classes yourself

**Comment by Sinfolke** [comment]
it was basically not matter as i remember. I have no sources, but if i remember correctly the basic function fault. Like:
File.ts:
   export function log(x) { print(x) }
main.ts:
   import { log } from File.ts
   function main() {
      log(1);
   }

I was compiling into executable to cause the error. The jit didn't solve as well as remove out .ts file.

If in your current build on windows the example above doesn't fails it's unlikely the bug is still there.

I'm using windows11 and my computer is not outdated to relate it to the hardware

**Comment by ASDAlexander77** [comment]
> import { log } from File.ts

Yes, the compiler supports only basic import but in your code u are trying to unwrap object and extract function out of it but export is returning function.

you need to write

```TypeScript```
...
import './File'

function main()
{
   log(1);
}
```
