### ISSUE TITLE
How to debug breakpoints

### ISSUE THREAD

**Issue by whaqzhzd** [ASDAlexander77/TypeScriptCompiler#106]
Greetings. I have successfully compiled the exe. Now I have a new question, can I debug typescript? Either use vscode or chrome dev.

**Comment by ASDAlexander77** [comment]
you can add option "--di" to include debug info. in the next release it will be working with --emit=exe now you can generate "obj" file and make exe with link.exe , then you can use vscode to debug it, (it will not work in chrome)

**Comment by whaqzhzd** [comment]
Thanks, I'll try it and look forward to the next version

**Comment by ASDAlexander77** [comment]
new release, debug info for executable should work. so when u compile use full path for filename, it would be easier for debugger to find file in debug mode to show debug progress properly
