### ISSUE TITLE
cannot support union types

### ISSUE THREAD

**Issue by lixiangsheng2018** [ASDAlexander77/TypeScriptCompiler#12]
hi,there, 
```
var val:string|number;
val = 12 
print(val) 
```
when use this ,there arised segment fault at print(val) ,any ideas ?

**Comment by ASDAlexander77** [comment]
right code would look like that

```
	var val:string|number;
	val = 12.0
	if (typeof(val) == "number")
	{
		print(val) 
	}

```

**Comment by ASDAlexander77** [comment]
and it is recommended to use "const/let" instead of "var" (var will create global variable)
