### ISSUE TITLE
How to support gc compile ?

### ISSUE THREAD

**Issue by lixiangsheng2018** [ASDAlexander77/TypeScriptCompiler#13]
I noticed that the readme.md compile with nogc?
./tsc --emit=jit -nogc -dump-object-file -object-filename=$1.o $1.ts

do this support gc ? how to enable gc compile ?

**Comment by ASDAlexander77** [comment]
check this folder and find which compile strategy is best for you  https://github.com/ASDAlexander77/TypeScriptCompiler/tree/main/docs/how/compile_binary

**Comment by ASDAlexander77** [comment]
or run as jit

`C:\TypeScriptCompiler\__build\tsc\bin\tsc.exe --emit=jit --shared-libs=C:\TypeScriptCompiler\__build\tsc\bin\TypeScriptRuntime.dll C:\helloworld.ts`

**Comment by lixiangsheng2018** [comment]
I tried enable GC on ubuntu,but get those error:
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %6, i8* null), !dbg !7
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %3, i8* null), !dbg !7
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %2, i8* null), !dbg !10
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %5, i8* null), !dbg !14
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %3, i8* null), !dbg !14
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %3, i8* null), !dbg !17
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %6, i8* null), !dbg !25
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %3, i8* null), !dbg !25
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %2, i8* null), !dbg !28
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %3, i8* null), !dbg !31
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %3, i8* null), !dbg !37
Enclosing function does not use GC.
  call void @llvm.gcroot(i8** %4, i8* null), !dbg !37
tsc: /home/lxs/disk/study/typescript/TypeScriptCompiler/tsc/tsc/tsc.cpp:494: int runJit(mlir::ModuleOp): Assertion `maybeEngine && "failed to construct an execution engine"' failed.
Aborted (core dumped)
does ubuntu support this ?

**Comment by ASDAlexander77** [comment]
restore everything as is.  download compiled release for Ubuntu here https://github.com/ASDAlexander77/TypeScriptCompiler/releases/download/v0.0-pre-alpha19/tsc.tar.gz

the difference only in lib name instead of TypeScriptRuntime.dll type libTypeScriptRuntime.so

**Comment by ASDAlexander77** [comment]
or try to learn procedure  createCompileBatchFileGC in file test-runner.cpp

**Comment by lixiangsheng2018** [comment]
ok, thanks it works

**Comment by lixiangsheng2018** [comment]
those works
------------------------------------------------------------------------------------
if you want to compile binary to execute, you need

tsc --emit=llvm file.ts > file.ll
llc -relocation-model=pic --filetype=obj -o=file.o file.ll
gcc file.o -lgcmt-lib -frtti -fexceptions -lstdc++ -lm -lpthread -ltinfo
