### ISSUE TITLE
Integer types

### ISSUE THREAD

**Issue by DiThi** [ASDAlexander77/TypeScriptCompiler#16]
I started a project with this compiler in mind (although it won't be the only target) and I realized I will need integer types. I can't find any reference to integers in the repository. I will be using [AssemblyScript's typedefs](https://github.com/AssemblyScript/assemblyscript/blob/main/std/portable/index.d.ts) for now. If integer support is added I think it will be a good idea to use the same ones (i8, i16, i32, isize, u8, u16, u32, usize, f32, f64).

**Comment by ASDAlexander77** [comment]
you need to have a look into "how to" file"\TypeScriptCompiler\docs\how\cmake_winapp\src\window.win32.d.ts".  You can see how you can create your integer types as the following: 

`
type uint32_t = TypeOf<1>;
type uint64_t = TypeOf<4294967297>;
type intptr_t = TypeOf<4294967297>;
`

**Comment by DiThi** [comment]
Cool! I can use this for now but I may need 8/16 bit types in the future. Also, typed arrays or similar? Should I open an issue for that?

**Comment by ASDAlexander77** [comment]
```
function testNumCollection(): void {
    let collXYZ: number[] = [];
    assert(collXYZ.push(42) == 1, "push count");
    assert(collXYZ.length == 1, "length");
    assert(collXYZ[0] == 42, "value");

    assert(collXYZ.pop() == 42, "pop value");
    assert(collXYZ.length == 0, "length after pop");
}

function main() {
    testNumCollection();
    print("done.");
}
```
