### ISSUE TITLE
Emscripten support?

### ISSUE THREAD

**Issue by alienself** [ASDAlexander77/TypeScriptCompiler#19]
Hi!

Great project but how can I integrate the compiled code to emscripten?
Would it be possible to compile the code to a static or dynamic library that can be called from an emscripten / c++ project?

Thanks a lot

**Comment by ASDAlexander77** [comment]
I didn't think about it.  Let me do research about it.

**Comment by alienself** [comment]
Sounds good! Would be really awesome if this was possible.

**Comment by ASDAlexander77** [comment]
ok. so EMCC have LLC command which can compile codes into WASM.  Have a look into folder https://github.com/ASDAlexander77/TypeScriptCompiler/tree/main/docs/how/wasm . There u can see example how to call "C" code from TS native code or other way around. Will continue digging

**Comment by alienself** [comment]
Ideally it would be great if we could compile this down to a dynamic library that could be loaded at runtime by emscripten as shown here: https://emscripten.org/docs/compiling/Dynamic-Linking.html
Do you think that would be possible?

Additionally, do you think it would be possible to call c++ / emscripten functions from typescript native?

Adding those features would for sure be game changing!

**Comment by ASDAlexander77** [comment]
I was thinking to implement DLLs but no progress in that direction yet

**Comment by ASDAlexander77** [comment]
there is experimental options to compile for EMCC 

```cmd
tsc.exe --emit=exe --nogc -mtriple=wasm32-pc-emscripten 1.ts
```
