### ISSUE TITLE
`libTypeScriptRuntime.so.13git` not found in released tarball

### ISSUE THREAD

**Issue by ApsarasX** [ASDAlexander77/TypeScriptCompiler#5]
I have downloaded the [released tarball](https://github.com/ASDAlexander77/TypeScriptCompiler/releases/download/v0.0-pre-alpha6/tsc.tar.gz) and decompressed it.

It just like:
![image](https://user-images.githubusercontent.com/24390069/138044552-c95bfb69-cfa1-4024-a55f-173ef72dbc0d.png)

There is an invalid symbolic link for lack of `libTypeScriptRuntime.so.13git`

**Comment by ASDAlexander77** [comment]
resolved
