### ISSUE TITLE
Rename the excecutame to something different from tsc

### ISSUE THREAD

**Issue by pdenapo** [ASDAlexander77/TypeScriptCompiler#57]
The standard typescript compiler from Microsoft (that transpiles to javascript) is also called tsc.
(https://aka.ms/tsc)

I think that it would be better to rename the executable of your project to something else (like llvm-tsc for instance) since I think that 
then testing it it is useful to have both programs installed in your system, and this would avoid some unnecessary possible confusion.

This might also cause trouble in the future when some linux distribution might want to package your compiler, as all the different binaries are usually kept together in the same directory (/usr/bin)

**Comment by ASDAlexander77** [comment]
Thank you for sugesstions, It is awlays dificult to find out right name, especially for me.
