### ISSUE TITLE
generate unexpected llvm ir

### ISSUE THREAD

**Issue by ApsarasX** [ASDAlexander77/TypeScriptCompiler#6]
version: Release v0.0-pre-alpha6
code: 
```ts
function func() {
    throw "123";
}

function main() {
    try {
        func();
    } catch {
        
    }
    return;
}
```

**Comment by ASDAlexander77** [comment]
have a look into .github\workflows\cmake-test-release-linux.yml . It will give u an idea how to compile it quickly. otherwise u may need to compile LLVM for hours

**Comment by ASDAlexander77** [comment]
resolved
