### ISSUE TITLE
Support for Imports

### ISSUE THREAD

**Issue by syrusakbary** [ASDAlexander77/TypeScriptCompiler#8]
It would be great, if Typescript projects that are using the `import` syntax to import variables, functions, classes or types could be compiled with tsc.

I tried the following:

```ts
import x from "./x";
```

And then tried to compile it, but it failed with "unknown statement type":
```bash
➜  tsc git:(main) ✗ ../__build/tsc-ninja/bin/tsc ../example.ts --emit=jit --nogc
unknown statement type
```

Thoughts?

**Comment by ASDAlexander77** [comment]
"Import" is not working for now, it is planned feature for future after generics. But can't say when and how I will implement it.

**Comment by coderaiser** [comment]
Would be amazing to have `imports` support. Everybody uses `imports` but not everybody uses `generics` :).

**Comment by ASDAlexander77** [comment]
it can be most difficult part of the project.  Because it is generated into obj files you can use "export" and "declare" to split code into many files for now

**Comment by ASDAlexander77** [comment]
added "/// reference" support in the last commit

**Comment by syrusakbary** [comment]
Hey @ASDAlexander77 any suggestion on how to use the mentioned `/// reference` support?

Eager to start using it!

**Comment by ODuzhar** [comment]
check the code in TypeScriptCompiler\docs\how\cmake_vulkan\src\  but keep it in mind that compiler is in progress and requires a lot of debugging etc

**Comment by lixiangsheng2018** [comment]
HI!, is import completed ? will you support import from so in the future?

**Comment by ASDAlexander77** [comment]
yes, work is in progress, not sure to which level I will develop it, or how long will it take, but for now I am implementing very basic functionality for "import" (kind of /// <reference path="window.win32.d.ts" />)

**Comment by syrusakbary** [comment]
That's an awesome first step @ASDAlexander77.
Do you know if importing types or variables by name would work? Is the `/// <reference ...>` tag always required?

**Comment by ASDAlexander77** [comment]
>> Is the /// <reference ...> tag always required?

no, you don't need it if you don't use anything from the referenced file

**Comment by ASDAlexander77** [comment]
it seems I still need to improve it not to use "/// <reference ...>"

**Comment by ASDAlexander77** [comment]
> That's an awesome first step @ASDAlexander77. Do you know if importing types or variables by name would work? Is the `/// <reference ...>` tag always required?

you don't need to use <reference ...> in the last commit

**Comment by ASDAlexander77** [comment]
> Do you know if importing types or variables by name would work?

not at this moment. and I am not sure if I need to impalement it, as it is not "JVM" and import working differently

**Comment by azarus** [comment]
> "Import" is not working for now, it is planned feature for future after generics. But can't say when and how I will implement it.

Would be great to see, Then we could slap some socket libs to it and roll an HTTP server out ez : ))

I'd recommend making the import process similar to how
```
#pragma link library
```

works, allowing us to include C++ libs on demand too if possible?

**Comment by ASDAlexander77** [comment]
I think I will do import the way how C++ include DLL files

**Comment by cunev** [comment]
I think also a possibility for implementing imports is to bundle it using existing bundlers such as ESBuild and then just compile?

I can't see why this wouldn't work if bundlers would generate/output TS files.

**Comment by ASDAlexander77** [comment]
> esbuild

well, when u compile every file you get OBJs files, then "Link" will join them into 1 file.  Seems what esbuild does.

**Comment by ASDAlexander77** [comment]
added additional way to import share libraries

**Comment by cereschen** [comment]
> added additional way to import share libraries

Try import  get the error

<unknown>:0: error: redefinition of symbol named '__decls'
<unknown>:0: note: see existing symbol definition here
.\src\use_shared.ts:1:1: error: module verification error
import Service from "./shared";
^

**Comment by ASDAlexander77** [comment]
Can u share your source code and compilation steps?

**Comment by cereschen** [comment]
> Can u share your source code and compilation steps?
```ts
// shared.ts
export default class Service {
}
```
```ts
// use_shared.ts
import Service from "./shared";

class MyComponent {
    constructor(public Service: Service) {
    }

    method(x: this) {
    }
}

function main()
{
	const myComponent = new MyComponent(null);
	print("done.");
}
```
run `D:\tsc\tsc.exe --opt --emit=jit --nogc .\src\use_shared.ts`

**Comment by ASDAlexander77** [comment]
you need to use latest from ``main`` branch. I am planning to release new build after improving "wasm" support
