### ISSUE TITLE
Please allow to call c/c++/rust libraries dynamic .dll and static .lib

### ISSUE THREAD

**Issue by sirlordt** [ASDAlexander77/TypeScriptCompiler#9]
Hello there.

I belive is great feature you can use c/c++/libraries.

**Comment by ASDAlexander77** [comment]
check example project at "\TypeScriptCompiler\docs\how\cmake_winapp\" maybe it can be useful to see how to use TSC with static libs

**Comment by sirlordt** [comment]
Thanks. But. Have examples for linux?

**Comment by ASDAlexander77** [comment]
check folder "\TypeScriptCompiler\docs\how\compile_binary\linux\" to see example how to compile for linux.  or u need cmake?
