### ISSUE TITLE
How to inline asm ?

### ISSUE THREAD

**Issue by zswDev** [ASDAlexander77/TypeScriptCompiler#93]
I want to implement syscall，
Inline compilation required，
1、linux syscall

**Comment by ASDAlexander77** [comment]
if you compile all into EXE(executable) file

1) create C file with all functions u need to do
2) add **declare function <name_of_c>(p1: TypeOf<1>)** etc
3) when compile code add OBJ file from C file

done.

have a look into `\docs\how\` to see how to use TSC with C/C++ compilers
