### ISSUE TITLE
Is it possible to use an npm library with the TypeScript Compiler?

### ISSUE THREAD

**Issue by HarunaMahjong** [ASDAlexander77/TypeScriptCompiler#94]
@ASDAlexander77 

Is it possible to use an npm library with the TypeScript Compiler?

Also, I would like to know if the current TypeScript Compiler supports all the syntax of TypeScript.

**Comment by ASDAlexander77** [comment]
No, it does not support Npm. As this is native computer as c++  not all features such as mixins are supporyed. Have a look at test folder to understand of scope of supported syntax structures
